//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetroSet_UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MetroSet_UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;MetroSetTheme&gt;
        ///  &lt;Theme&gt;
        ///    &lt;Name&gt;DarkUI&lt;/Name&gt;
        ///    &lt;Author&gt;Narwin&lt;/Author&gt;
        ///  &lt;/Theme&gt;
        ///  &lt;Form&gt;
        ///    &lt;Enabled&gt;true&lt;/Enabled&gt;
        ///    &lt;ForeColor&gt;#293955&lt;/ForeColor&gt;
        ///    &lt;BackColor&gt;#1e1e1e&lt;/BackColor&gt;
        ///    &lt;BorderColor&gt;#b72828&lt;/BorderColor&gt;
        ///    &lt;SmallLineColor1&gt;#F11199&lt;/SmallLineColor1&gt;
        ///    &lt;SmallLineColor2&gt;#EA5216&lt;/SmallLineColor2&gt;
        ///    &lt;TextColor&gt;#ffffff&lt;/TextColor&gt;
        ///    &lt;DrawLeftRect&gt;true&lt;/DrawLeftRect&gt;
        ///    &lt;DisplayHeader&gt;true&lt;/DisplayHeader&gt;
        ///    &lt;TextAlign&gt;left&lt;/TextAlign&gt;	
        ///    &lt;SmallRectThickne [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MetroSet_Theme {
            get {
                return ResourceManager.GetString("MetroSet_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SegoeWP {
            get {
                object obj = ResourceManager.GetObject("SegoeWP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SegoeWP_Bold {
            get {
                object obj = ResourceManager.GetObject("SegoeWP_Bold", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SegoeWP_Light {
            get {
                object obj = ResourceManager.GetObject("SegoeWP_Light", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SegoeWP_Semibold {
            get {
                object obj = ResourceManager.GetObject("SegoeWP_Semibold", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SegoeWP_Semilight {
            get {
                object obj = ResourceManager.GetObject("SegoeWP_Semilight", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
